Repository pulp/pulp_rpm, pull requests merged in 2018-10, with the labels that each got.

#1200 Add test to sync/publish update references
  pulp_rpm/tests/functional/api/test_publish.py
  pulp_rpm/tests/functional/api/test_sync.py
  pulp_rpm/tests/functional/constants.py
  pulp_rpm/tests/functional/utils.py
Labels: 3.0, Tests

#1208 Fix link to the docs
  README.rst
Labels: 3.0, Documentation

#1211 Fix filename gen code
  pulp_rpm/app/models.py
Labels: 3.0

#1213 Release notes for 2.17.1
  docs/user-guide/release-notes/2.17.x.rst
Labels: Documentation
