Repository pulp/pulp_rpm, pull requests merged in 2018-09, with the labels that each got.

#1186 Compile and install createrepo_c so that we can run smash tests
  .travis/install.sh
  .travis/script.sh
Labels: 3.0

#1183 Store UpdateReference
  pulp_rpm/app/constants.py
  pulp_rpm/app/models.py
  pulp_rpm/app/tasks/synchronizing.py
Labels: 3.0

#1180 As a user, I can publish rpms and errata
  README.rst
  pulp_rpm/app/tasks/publishing.py
  pulp_rpm/tests/functional/api/test_publish.py
Labels: 3.0

#1187 Remove modular RPMs if a module is getting removed
  plugins/pulp_rpm/plugins/importers/yum/importer.py
Labels: bugfix

#1192 Use digest for uniqueness constraint for UpdateRecord
  pulp_rpm/app/models.py
Labels: 3.0, bugfix

#1198 Update README with instructions on installing createrepo_c
  README.rst
Labels: 3.0, Documentation

#1197 Only show checksum if it's not blank
  pulp_rpm/app/tasks/publishing.py
Labels: 3.0

#1176 Add upload support, enable CRUD PackageContent tests
  README.rst
  pulp_rpm/app/models.py
  pulp_rpm/app/serializers.py
  pulp_rpm/app/viewsets.py
  pulp_rpm/tests/functional/api/test_crud_content_unit.py
  pulp_rpm/tests/functional/api/test_download_content.py
  pulp_rpm/tests/functional/constants.py
  pulp_rpm/tests/functional/utils.py
Labels: 3.0, Tests, enhancement

#1201 Add docs
  README.rst
  docs/Makefile
  docs/_static/.this_makes_it_so_git_keeps_the__static_folder
  docs/conf.py
  docs/index.rst
  docs/installation.rst
  docs/release-notes/3.0.z.rst
  docs/workflows/create_sync_publish.rst
  docs/workflows/index.rst
  docs/workflows/upload.rst
  docs/workflows/use_pulp_repo.rst
Labels: 3.0, Documentation
