Repository pulp/pulp_rpm, pull requests merged in 2019-03, with the labels that each got.

#1290 Add test single request upload
  pulp_rpm/tests/functional/api/test_upload.py
Labels: 3.0, Tests

#1289 Add docs describing behavior of recursive flags
  docs/tech-reference/yum-plugins.rst
  docs/user-guide/features.rst
Labels: Documentation

#1301 Handle duplicated modular collections in errata at publish time
  plugins/pulp_rpm/plugins/distributors/yum/publish.py
Labels: bugfix

#1302 Add release notes for 2.19.0
  docs/user-guide/release-notes/2.19.x.rst
  docs/user-guide/release-notes/index.rst
Labels: Documentation

#1299 Fix test SyncPublishDownloadPolicyTestCase
  pulp_rpm/tests/functional/api/test_download_policies.py
Labels: 3.0, Tests

#1298 Fix publish for the on_demand sync case
  pulp_rpm/app/models.py
  pulp_rpm/app/tasks/publishing.py
Labels: 3.0, bugfix

#1308 Update docs to use UUIDs
  docs/workflows/create_sync_publish.rst
  docs/workflows/upload.rst
Labels: 3.0, Documentation

#1309 Fix upload docs, add description of on_demand policy
  docs/workflows/create_sync_publish.rst
  docs/workflows/upload.rst
Labels: 3.0, Documentation

#1310 Prepare for beta 2
  docs/release-notes/3.0.z.rst
  setup.py
Labels: 3.0
