Repository pulp/pulp_rpm, pull requests merged in 2022-01, with the labels that each got.

#2202 Fix distribution tree sync for repos with partial .treeinfo files
  CHANGES/2305.bugfix
  pulp_rpm/app/migrations/0039_disttree_digest.py
  pulp_rpm/app/models/distribution.py
  pulp_rpm/app/tasks/synchronizing.py
Labels: Needs Cherry Pick

#2168 [Pulp 2] Fix broken repodata signing if sqlite is enabled
  common/pulp_rpm/common/constants.py
  plugins/pulp_rpm/plugins/distributors/yum/metadata/repomd.py
  plugins/pulp_rpm/plugins/distributors/yum/publish.py
  plugins/pulp_rpm/yum_plugin/util.py
Labels: Pulp 2, Needs Cherry Pick

#2357 Fix data migration for pulp_rpm 3.17.0
  CHANGES/2356.bugfix
  pulp_rpm/app/migrations/0039_disttree_digest.py
Labels: backport-3.17

#2362 Add a utility script for trimming changelogs in DB
  CHANGES/2361.misc
  pulp_rpm/app/management/__init__.py
  pulp_rpm/app/management/commands/__init__.py
  pulp_rpm/app/management/commands/trim_rpm_changelogs.py
  setup.py
Labels: backport-3.17

#2359 Apply a sort prior to the changelog limit
  CHANGES/2363.bugfix
  pulp_rpm/app/metadata_parsing.py
Labels: backport-3.17, backport-3.14

#2344 Added a debug option for observability into depsolving
  CHANGES/2343.feature
  pulp_rpm/app/depsolving.py
  pulp_rpm/app/settings.py
  pulp_rpm/app/tasks/copy.py
Labels: backport-3.17

#2367 Fix paths for addons
  CHANGES/2373.bugfix
  pulp_rpm/app/kickstart/treeinfo.py
Labels: backport-3.17, backport-3.14

#2380 Make sure more file descriptors are closed properly
  CHANGES/2379.bugfix
  pulp_rpm/app/tasks/publishing.py
Labels: backport-3.17, backport-3.14, backport-3.11
