Repository pulp/pulp_rpm, pull requests merged in 2022-08, with the labels that each got.

#2687 Don't raise a fatal error when encountering unexpected metadata
  CHANGES/2686.bugfix
  pulp_rpm/app/tasks/synchronizing.py
Labels: backport-3.17, backport-3.14

#2683 Check if open_size_element has text attribute
  plugins/pulp_rpm/plugins/importers/yum/repomd/metadata.py
Labels: Pulp 2

#2693 Ensure that Pulp never publishes repos with duplicate NEVRA
  CHANGES/2407.bugfix
  pulp_rpm/app/tasks/publishing.py
Labels: backport-3.17, backport-3.14

#2668 Allow syncing duplicate NEVRAs, pick the newest one
  CHANGES/2691.bugfix
  pulp_rpm/app/tasks/synchronizing.py
  pulp_rpm/tests/functional/api/test_retention_policy.py
Labels: backport-3.17, backport-3.14

#2714 Do not sync optimize if retain-package-versions was set/changed
  CHANGES/2704.bugfix
  pulp_rpm/app/tasks/synchronizing.py
Labels: backport-3.17
