Repository pulp/pulp_rpm, pull requests merged in 2023-02, with the labels that each got.

#2927 Allow "group" aka comps metadata to be compressed
  CHANGES/2753.bugfix
  pulp_rpm/app/modulemd.py
  pulp_rpm/app/shared_utils.py
  pulp_rpm/app/tasks/comps.py
  pulp_rpm/app/tasks/synchronizing.py
Labels: backport-3.17, backport-3.18

#2953 Fix a failure scenario that can occur in migration from 3.17 to 3.18
  CHANGES/2952.bugfix
  pulp_rpm/app/migrations/0045_modulemd_fields.py
  pulp_rpm/app/models/modulemd.py
Labels: backport-3.18

#2968 Fix a minor parsing bug that causes pulp-to-pulp sync to fail
  CHANGES/2961.bugfix
  pulp_rpm/app/modulemd.py
  pulp_rpm/app/tasks/publishing.py
Labels: backport-3.19

#2966 Refactor copy tests to follow the pytest standard
  CHANGES/2874.misc
  pulp_rpm/tests/functional/api/test_copy.py
  pulp_rpm/tests/functional/conftest.py
Labels: backport-3.18, backport-3.19
