Repository pulp/pulp_rpm, pull requests merged in 2023-06, with the labels that each got.

#3002 Fixed data-fixup-during-sync deadlock.
  CHANGES/2980.bugfix
  pulp_rpm/app/tasks/synchronizing.py
Labels: backport-3.17, backport-3.18, backport-3.19, backport-3.21, backport-3.22

#3171 Don't write invalid characters to a repo id, even if the distro name contains them.
  CHANGES/3170.bugfix
  pulp_rpm/app/models/repository.py
Labels: backport-3.22

#3182 Made migration more robust when there are "broken" modulemds.
  CHANGES/3177.bugfix
  pulp_rpm/app/migrations/0048_artifacts_dependencies_fix.py
Labels: backport-3.19, backport-3.21, backport-3.22
