Repository pulp/pulp_rpm, pull requests merged in 2024-10, with the labels that each got.

#3736 Ignore 'prn' field on metadata comparision tests
  pulp_rpm/tests/functional/api/test_sync.py
Labels: no-issue, no-changelog

#3746 [3.26] Ignore 'prn' field on metadata comparing tests
  pulp_rpm/tests/functional/api/test_sync.py
Labels: no-issue, no-changelog

#3745 [3.27] Ignore 'prn' field on metadata comparing tests
  pulp_rpm/tests/functional/api/test_sync.py
Labels: no-issue, no-changelog

#3744 [3.25] Ignore 'prn' field on metadata comparing tests
  pulp_rpm/tests/functional/api/test_sync.py
Labels: no-issue, no-changelog

#3747 Drop 3.18 and 3.19 from supported branches
  template_config.yml
Labels: no-issue, no-changelog

#3757 Fixed create_modulemd() stacktrace when handling malformed modulmd.
  CHANGES/3756.bugfix
  pulp_rpm/app/modulemd.py
Labels: backport-3.22, backport-3.23, backport-3.25, backport-3.27, backport-3.26

#3763 Change 3614 into a bugfix
  CHANGES/3614.bugfix
Labels: backport-3.25, backport-3.27, backport-3.26, no-issue

#3767 [3.26] Fix ruby bindings AnyType error
  CHANGES/3639.bugfix
  pulp_rpm/app/fields.py
  pulp_rpm/app/serializers/advisory.py
  pulp_rpm/app/serializers/comps.py
  pulp_rpm/app/serializers/modulemd.py
  pulp_rpm/app/serializers/package.py
  pulp_rpm/app/serializers/repository.py
Labels: no-issue
