Repository pulp/pulp_rpm, pull requests merged in 2025-08, with the labels that each got.

#4066 [PULP-36285] Bump create_repo_c requirement to allow 1.2.1
  requirements.txt
Labels: no-issue, no-changelog

#4068 Bump minimum supported pulpcore
  pyproject.toml
Labels: no-issue, no-changelog, backport-3.31

#4088 Bump libcomps [3.29]
  pyproject.toml
Labels: backport-3.23, backport-3.26, no-issue, no-changelog, backport-3.27

#4089 Add storage settings to template_config.yml
  template_config.yml
Labels: backport-3.23, backport-3.26, no-issue, no-changelog
