Repository pulp/pulp_rpm, pull requests merged in 2025-04, with the labels that each got.

#3928 Refactor the fixtures as a pytest plugin
  CHANGES/+pytest_plugin.misc
  pulp_rpm/pytest_plugin.py
  pyproject.toml
Labels: no-issue

#3947 Fix a sync memory consumption issue w/ modular repos
  CHANGES/3311.bugfix
  pulp_rpm/app/modulemd.py
Labels: backport-3.22, backport-3.23, backport-3.25, backport-3.26, backport-3.29, backport-3.27

#3948 Update supported branches to correct active set.
  .github/workflows/update_ci.yml
  template_config.yml
Labels: no-issue, no-changelog

#3959 Remove gettext from one small warning message
  pulp_rpm/app/tasks/synchronizing.py
Labels: no-issue, no-changelog
