Repository pulp/pulp_rpm, pull requests merged in 2025-09, with the labels that each got.

#4070 [PULP-435] Enforce relative_path matches the package name
  CHANGES/4073.bugfix
  pulp_rpm/app/management/commands/rpm-datarepair.py
  pulp_rpm/app/tasks/publishing.py
  pulp_rpm/app/tasks/synchronizing.py
  pulp_rpm/tests/functional/api/test_sync.py
Labels: no-issue, backport-3.29

#4133 4117 rework
  CHANGES/4117.bugfix
  pulp_rpm/app/tasks/publishing.py
  pulp_rpm/app/tasks/synchronizing.py
Labels: multi-commit, no-issue

#4135 Update docs about client bindings
  CHANGES/+update-bindings.docs
  docs/dev/guides/bindings.md
Labels: no-issue, no-changelog

#4147 Replace django.utils.timezone.utc by datetime.timezone.utc
  CHANGES/+update-timezone.misc
  pulp_rpm/app/tasks/prune.py
Labels: no-issue

#4152 Add tests for package sorting and fix algorithm [3.29]
  pulp_rpm/app/rpm_version.py
  pulp_rpm/tests/unit/test_package_age.py
  pulp_rpm/tests/unit/test_rpm_version.py
Labels: multi-commit, no-issue, no-changelog

#4154 Add tests for package sorting and fix algorithm [3.26]
  pulp_rpm/app/rpm_version.py
  pulp_rpm/tests/unit/test_package_age.py
  pulp_rpm/tests/unit/test_rpm_version.py
Labels: multi-commit, no-issue, no-changelog
