Repository pulp/pulp_rpm, pull requests merged in 2025-06, with the labels that each got.

#3987 [3.29] Significantly improve publish performance
  CHANGES/+publish-perf.bugfix
  pulp_rpm/app/models/package.py
  pulp_rpm/app/serializers/repository.py
  pulp_rpm/app/tasks/publishing.py
  pulp_rpm/app/tasks/synchronizing.py
Labels: no-issue, backport-3.27

#3989 [3.26] Significantly improve publish performance
  CHANGES/+publish-perf.bugfix
  pulp_rpm/app/models/package.py
  pulp_rpm/app/serializers/repository.py
  pulp_rpm/app/tasks/publishing.py
  pulp_rpm/app/tasks/synchronizing.py
Labels: no-issue

#3993 Remove deprecated TaskGroup.finish calls
  CHANGES/3985.misc
  pulp_rpm/app/tasks/prune.py
  pulp_rpm/app/viewsets/acs.py
Labels: no-issue

#3996 [PULP-604] Ensure Repository.package_signing_fingerprint doesnt return None
  CHANGES/3995.bugfix
  pulp_rpm/app/serializers/repository.py
Labels: no-issue, backport-3.29, backport-3.27, backport-3.30

#4005 [backport 3.27] Ensure Repository.package_signing_fingerprint doesnt return None
  CHANGES/3995.bugfix
  pulp_rpm/app/serializers/repository.py
Labels: no-issue
